{% set name = "intervalues" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 551b4c2fea5e7e9c893a6df846756fe5d173fe900492c04034df12e48b837471

build:
  number: 0
  skip: True  # [py<310]
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
    - cd rust && cargo-bundle-licenses --format yaml --output ../THIRDPARTY.yml

requirements:
  build:
    - {{ compiler("rust") }}
    - {{ stdlib("c") }}
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - crossenv                            # [build_platform != target_platform]
    - cargo-bundle-licenses
  host:
    - python
    - setuptools >=61.0
    - setuptools-rust
    - pip
  run:
    - python
    - libgcc  # [linux]

test:
  imports:
    - intervalues
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/bert.debruijn/intervalues
  dev_url: https://gitlab.com/bert.debruijn/intervalues
  summary: Efficient combining of intervals of numbers.
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - apcamargo
